// Action types

export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const INCREMENT_FLASH_MESSAGE = 'INCREMENT_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGES = 'DELETE_FLASH_MESSAGES';
export const SET_SESSION_DATA = 'SET_SESSION_DATA';
